name: "🏷️ Action › Release › Post"
run-name: "🏷️ Action › Release › Post"

on:
  release:
    types:
      - published
      - edited

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
