name: "🏷️ Action › Release › @latest"
run-name: "🏷️ Action › Release › @latest"

on:
  release:
    types:
      - published
      - edited

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: "☑️ Checkout"
        id: task_cloudflare_checkout
        uses: actions/checkout@v4

      - name: "🏷️ Update @latest build"
        uses: Actions-R-Us/actions-tagger@latest
        with:
          token: ${{ secrets.ADMINSERV_TOKEN_CL }}
          publish_latest_tag: true
